# Generated by Django 4.0.1 on 2022-01-25 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SensorType',
            new_name='SensorTypes',
        ),
    ]
