# Generated by Django 4.0.1 on 2022-01-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_rename_sensortype_sensortypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensortypes',
            name='humidity_precision',
            field=models.FloatField(default=False),
        ),
        migrations.AddField(
            model_name='sensortypes',
            name='pressure_precision',
            field=models.FloatField(default=False),
        ),
        migrations.AddField(
            model_name='sensortypes',
            name='reads_humidity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sensortypes',
            name='reads_pressure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sensortypes',
            name='reads_temperature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sensortypes',
            name='temperature_precision',
            field=models.FloatField(default=False),
        ),
    ]
