# Generated by Django 4.0.1 on 2022-01-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_sensortypes_humidity_precision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensortypes',
            name='humidity_precision',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sensortypes',
            name='pressure_precision',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sensortypes',
            name='temperature_precision',
            field=models.FloatField(default=0, null=True),
        ),
    ]
