# Generated by Django 4.0.1 on 2022-01-25 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_alter_sensortypes_humidity_precision_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensortypes',
            old_name='reads_humidity',
            new_name='humidity_reads',
        ),
        migrations.RenameField(
            model_name='sensortypes',
            old_name='reads_pressure',
            new_name='pressure_reads',
        ),
        migrations.RenameField(
            model_name='sensortypes',
            old_name='reads_temperature',
            new_name='temperature_reads',
        ),
    ]
