# Generated by Django 4.0.1 on 2022-01-25 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_rename_reads_humidity_sensortypes_humidity_reads_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hwid', models.IntegerField(default=0, null=True)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=300)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sensors.sensortypes')),
            ],
        ),
    ]
