# Generated by Django 4.0.1 on 2022-01-25 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0006_sensors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensors',
            old_name='type',
            new_name='type_id',
        ),
        migrations.CreateModel(
            name='SensorLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(default=0, null=True)),
                ('humidity', models.FloatField(default=0, null=True)),
                ('pressure', models.FloatField(default=0, null=True)),
                ('create_at', models.DateTimeField()),
                ('sensor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sensors.sensors')),
            ],
        ),
    ]
