# Generated by Django 4.0.1 on 2022-01-25 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0007_rename_type_sensors_type_id_sensorlogs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SensorLogs',
            new_name='Sensor_Logs',
        ),
        migrations.RenameModel(
            old_name='SensorTypes',
            new_name='Sensor_Types',
        ),
    ]
